# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
locations = LocationCategory.create([{name: 'Historical'},{name:'Picnic'},{name:'Museum'},{name:'Advantured'},{name:'Temples'}])

locationCategory_id = Location.create([{name:'Krishna Pura Chhatri'},{zipcode:'452007'},{city:'Indore'},{state:'Madhya Pradesh '},{name:'Lal Baag Palace'},{zipcode:'452007'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Asirgarh Fort'},{zipcode:'450221'},{city:'Burhanpur'},{state:'Madhya Pradesh'},{name:'Rajwada
'},{zipcode:' 452002'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Bhopal Gate'},{zipcode:'462001'},{city:'Bhopal'},{state:'Madhya Pradesh'},{name:'Gauhar Mahal'},{zipcode:' 462001'},{city:'Bhopal'},{state:'Madhya Pradesh'},{name:'Shahi Qila'},{zipcode:' 450331'},{city:'Burhanpur'},{state:'Madhya Pradesh'},{name:'Sheesh Mahal'},{zipcode:' 452002'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Dhar Fort'},{zipcode:' 454001'},{city:'Dhar'},{state:'Madhya Pradesh'},{name:'Hukumchand Ghantaghar'},{zipcode:' 452001'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Gandhi Hall'},{zipcode:' 452007'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Rani Sati gate'},{zipcode:' 452003'},{city:'Indore'},{state:'Madhya Pradesh'},{name:'Sultania Infantry Gate'},{zipcode:'462001'},{city:'Bhopal'},{state:'Madhya Pradesh'},{name:'Putlighar Minar'},{zipcode:' 462001'},{city:'Bhopal'},{state:'Madhya Pradesh'},{name:'Junagarh Fort'},{zipcode:' 334001'},{city:'Bikner'},{state:'Rajashthan'},{name:'Ranthambore Fort'},{zipcode:'322001'},{city:'Sawai Madhopur'},{state:'Rajashthan'},{name:'Nahargarh Fort'},{zipcode:'302002'},{city:'Jaipur'},{state:'Rajashthan'},{name:'Adhai Din Ka Jhonpra'},{zipcode:'305001'},{city:'Ajmer'},{state:'Rajashthan'},{name:'Kotah Garh '},{zipcode:'324006'},{city:'Kota'},{state:'Rajashthan'}])